version: '3'
services:
  qtail:
    build: .
    container_name: 'qtail'
    restart: 'always'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.qtail.rule=Host(`localhost`)'
      - 'traefik.http.routers.qtail.entrypoints=web'
    environment:
      - 'ORIGIN=http://localhost'
    networks:
      - 'web'
    volumes:
      - 'files:/app/static/files'
      - 'db:/app/db'

  traefik:
    image: 'traefik:latest'
    container_name: 'traefik'
    restart: 'always'
    networks:
      - web
    command:
      - '--api.dashboard=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.dash.address=:8080'
      - '--entrypoints.web.address=:80'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dashboard.rule=Host(`localhost`)'
      - 'traefik.http.routers.dashboard.entrypoints=dash'
      - 'traefik.http.routers.dashboard.service=api@internal'
      - 'traefik.http.routers.dashboard.middlewares=auth'
      - 'traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$N9MTkji2$$QOyaU7gvHgMhl4wF3PO5l.'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

networks:
  web:
    driver: bridge

volumes:
  files:
    name: 'files'
  db:
    name: 'db'
