services:
  qtail:
    build: .
    container_name: 'qtail'
    restart: 'always'
    labels:
      - 'traefik.enable=true'
      # Routers
      - 'traefik.http.routers.qtail.rule=Host(`${EXPOSE_IP}`)'
      - 'traefik.http.routers.qtail.entrypoints=web'

      - 'traefik.http.routers.adminQtail.rule=Path(`/login`) && Query(`/login=`) && Method(`POST`)'
      - 'traefik.http.routers.adminQtail.entrypoints=web'
      - 'traefik.http.routers.adminQtail.middlewares=rateAdmin@docker'

      # Middlewares
      - 'traefik.http.middlewares.rateAdmin.ratelimit.average=5'
      - 'traefik.http.middlewares.rateAdmin.ratelimit.period=1m'

    environment:
      - 'BODY_SIZE_LIMIT=Infinity'
      - 'ORIGIN=http://${EXPOSE_IP}'
    networks:
      - 'web'
    volumes:
      - 'files:/app/files'
      - 'db:/app/db'
      - '/var/log/qtail/:/app/logs'

  traefik:
    image: 'traefik:latest'
    container_name: 'traefik'
    restart: 'always'
    environment:
      - 'TZ=EU/Rome'
    networks:
      - web
    command:
      - '--api.dashboard=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      # Entrypoints
      - '--entrypoints.dash.address=:8080'
      - '--entrypoints.web.address=:80'
      # Logs
      - '--accesslog=true'
      - '--accesslog.filepath=/logs/access.log'
      - '--log.level=INFO'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dashboard.rule=Host(`${EXPOSE_IP}`)'
      - 'traefik.http.routers.dashboard.entrypoints=dash'
      - 'traefik.http.routers.dashboard.service=api@internal'
      - 'traefik.http.routers.dashboard.middlewares=auth'
      - 'traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$N9MTkji2$$QOyaU7gvHgMhl4wF3PO5l.'
    ports:
      - target: 80
        published: 80
        mode: host
      - '8080:8080'
    volumes:
      - '/var/log/traefik:/logs'
      - '/var/run/docker.sock:/var/run/docker.sock'

networks:
  web:
    driver: bridge

volumes:
  files:
    name: 'files'
  db:
    name: 'db'
